version: 2.1

jobs:
    build-app:
        docker:
            - image: cimg/rust:1.59.0-node
        resource_class: medium
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - tauri-app-node-{{ arch }}-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
                      - tauri-app-node-{{ arch }}-{{ .Branch }}
                      - tauri-app-node-{{ arch }}-
                      - tauri-app-node-
            - restore_cache:
                  keys:
                      - tauri-app-cargo-{{ arch }}-{{ .Branch }}-{{ checksum "app/src-tauri/Cargo.lock" }}
                      - tauri-app-cargo-{{ arch }}-{{ .Branch }}-
                      - tauri-app-cargo-{{ arch }}
                      - tauri-app-cargo
            - run: |
                  sudo apt update && sudo apt install -y libwebkit2gtk-4.0-dev \
                  build-essential \
                  curl \
                  wget \
                  libssl-dev \
                  libgtk-3-dev \
                  libappindicator3-dev \
                  librsvg2-dev
            - run:
                  name: "Install npm tools"
                  command: "cd app && npm install"
            - run:
                  name: "Build app"
                  command:
                      "cd app && TAURI_PRIVATE_KEY=${UPDATE_SIGNING_KEY} TAURI_KEY_PASSWORD=${UPDATE_SIGNING_PASSWORD}
                      npm run tauri build"
            - persist_to_workspace:
                  destination: "artifacts"
                  root: "app/src-tauri/target/release/bundle"
                  paths: "appimage/demo_*.AppImage*"
            - save_cache:
                  key: tauri-app-node-{{ arch }}-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
                  paths:
                      - "app/node_modules"
            - run:
                  name: "Cache cleanup"
                  command: "rm -rf app/src-tauri/target/release/bundle"
            - save_cache:
                  key: tauri-app-cargo-{{ arch }}-{{ .Branch }}-{{ checksum "app/src-tauri/Cargo.lock" }}
                  paths:
                      - "app/src-tauri/target"
    release-app:
        docker:
            - image: cibuilds/github:0.10
        resource_class: small
        steps:
            - checkout
            - attach_workspace:
                  at: ./artifacts
            - run: "apk add jq"
            - run:
                  name: "Publish Release on GitHub"
                  command: |
                      VERSION=$(cat ./app/src-tauri/tauri.conf.json | jq -r '.package.version')
                      ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/appimage/

    notify-update:
        docker:
            - image: cimg/base:current
        resource_class: small
        steps:
            - checkout
            - attach_workspace:
                  at: ./artifacts
            - run: sudo apt install jq -y
            - run:
                  name: "Notify update server"
                  command: |
                      VERSION=$(cat ./app/src-tauri/tauri.conf.json | jq -r '.package.version')
                      SIGNATURE=$(cat ./artifacts/appimage/*.sig)
                      curl -d "version=${VERSION}&target=linux&url=https://github.com/corentinguilloteau/kth-devops-tauri-CD/releases/tag/${VERSION}&signature=${SIGNATURE}&auth=${UPDATE_SERVER_SECRET}" https://cg-dev.rezel.net/kthdevops/tauriupdaterdemo/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    deploy-app:
        jobs:
            - build-app
            - release-app:
                  requires:
                      - build-app
                  #filters:
                  #   branches:
                  #      only: main
