version: 2.1

jobs:
    build-app:
        docker:
            - image: cimg/rust:1.59.0-node
        resource_class: medium
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - tauri-app-node-{{ arch }}-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
                      - tauri-app-cargo-{{ arch }}-{{ .Branch }}-{{ checksum "app/src-tauri/Cargo.lock" }}
            - run: |
                  sudo apt update && sudo apt install libwebkit2gtk-4.0-dev \
                  build-essential \
                  curl \
                  wget \
                  libssl-dev \
                  libgtk-3-dev \
                  libappindicator3-dev \
                  librsvg2-dev
            - run:
                  name: "Install npm tools"
                  command: "cd app && npm install"
            - run:
                  name: "Build app"
                  command: "cd app && npm run tauri build"
            - persist_to_workspace:
                  destination: "artifacts"
                  root: "app/src-tauri/target/release/bundle"
                  paths: "appimage/*"
            - save_cache:
                  key: tauri-app-node-{{ arch }}-{{ .Branch }}-{{ checksum "app/package-lock.json" }}
                  paths:
                      - "app/node_modules"
            - save_cache:
                  key: tauri-app-cargo-{{ arch }}-{{ .Branch }}-{{ checksum "app/src-tauri/Cargo.lock" }}
                  paths:
                      - "app/src-tauri/target"
    release-app:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - checkout
            - attach_workspace:
                  at: ./artifacts
            - run: "apt install jq"
            - run:
                  name: "Publish Release on GitHub"
                  command: |
                      VERSION=$(cat ./app/src-tauri/tauri.conf.json | jq -y '.package.version')
                      ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    deploy-app:
        jobs:
            - build-app
            - release-app:
                  requires:
                      - build-app
