version: 2.1

jobs:
    build-app:
        docker:
            - image: cimg/rust:1.59.0
        steps:
            - checkout
            - run:
                  name: "Install tauri"
                  command: "cargo install tauri-cli --locked --version ^1.0.0-rc.8"
            - run:
                  name: "Build app"
                  command: "cargo tauri build"
            - persist_to_workspace:
                  root: "src-tauri/target/release/bundle"
                  paths: "appimage/*"

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    app:
        jobs:
            - build-app
