version: 2.1

jobs:
    build-app:
        docker:
            - image: cimg/rust:1.59.0-node
        steps:
            - checkout
            - run: "cd app"
            - run:
                  name: "Install tauri"
                  command: "cargo install tauri-cli --version ^1.0.0-rc.8"
            - run:
                  name: "Install npm tools"
                  command: "npm install"
            - run:
                  name: "Build app"
                  command: "cargo tauri build"
            - persist_to_workspace:
                  root: "src-tauri/target/release/bundle"
                  paths: "appimage/*"
    release-app:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - attach_workspace:
                  at: ./artifacts
            - checkout
            - run: "apt install jq"
            - run:
                  name: "Publish Release on GitHub"
                  command: |
                      VERSION=$(cat ./app/src-tauri/tauri.conf.json | jq -y '.package.version')
                      ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    app:
        jobs:
            - build-app
            - release-app
